wicket:
  configuration-type: development
  core:
    debugsettings:
      enabled: true
      component-use-check: true
      development-utilities-enabled: true
  wicketstuff:
    htmlcompressor:
      enabled: false
      features:
        removeComments: false
        removeMultiSpaces: false
        removeIntertagSpaces: false
        removeQuotes: false
        compressJavaScript: false
        compressCss: false
        simpleDoctype: false
        removeScriptAttributes: false
        removeStyleAttributes: false
        removeLinkAttributes: false
        removeFormAttributes: false
        removeInputAttributes: false
        simpleBooleanAttributes: false
        removeJavaScriptProtocol: false
        removeHttpProtocol: false
        removeHttpsProtocol: false
        preserveLineBreaks: false
  devutils:
    statelesschecker:
      enabled: true
    interceptor:
      enable-live-sessions-page: true
    diskstorebrowser:
      enabled: true
  wicketsource:
    enabled: true