security:
  basic:
    enabled: false
wicket:
  stuff:
    datastore:
      hazelcast:
        enabled: false
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
        - +*.map
server:
  compression:
    enabled: true
management:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml