wicket:
  stuff:
    datastore:
      hazelcast:
        enabled: false
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
        - +*.map
server:
  compression:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml